### ISSUE TITLE
ERROR from mc 1.8.8 PandaSpigot

### ISSUE THREAD

**Issue by postyizhan** [LagBug/ThePit#1]
PandaSpigot: https://github.com/hpfxd/PandaSpigot

`[22:19:35 ERROR]: Could not pass event EntityDamageEvent to ThePit v0.0.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:564) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:549) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:557) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:543) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:589) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1117) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:748) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at net.minecraft.server.v1_8_R3.EntityLiving.K(EntityLiving.java:211) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at net.minecraft.server.v1_8_R3.EntityInsentient.K(EntityInsentient.java:150) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at net.minecraft.server.v1_8_R3.Entity.t_(Entity.java:278) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1475) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at net.minecraft.server.v1_8_R3.EntityInsentient.t_(EntityInsentient.java:194) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1777) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at net.minecraft.server.v1_8_R3.World.g(World.java:1744) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1573) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:602) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:967) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:412) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:815) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:648) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_8_R3.entity.CraftPig cannot be cast to class org.bukkit.entity.Player (org.bukkit.craftbukkit.v1_8_R3.entity.CraftPig and org.bukkit.entity.Player are in unnamed module of loader 'app')
        at com.LagBug.ThePit.Events.OnFall.onFall(OnFall.java:17) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PandaSpigot-98]
        ... 25 more`

**Comment by LagBug** [comment]
Hey there, ThePit is no longer maintained. Feel free to folk and fix it if you'd like.
